# Generated by Django 4.2.7 on 2023-11-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
