# Generated by Django 5.0 on 2023-12-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0005_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto_imagenes/'),
        ),
    ]
