# Generated by Django 5.0 on 2023-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0007_trekking_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekking',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='trekking',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='trekking',
            name='precio',
        ),
    ]
