# Generated by Django 5.0 on 2023-12-13 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0008_remove_trekking_cupo_maximo_remove_trekking_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trekking',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_curso', 'En Curso'), ('cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
        migrations.AddField(
            model_name='trekking',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trekking',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
