# Generated by Django 5.0 on 2023-12-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0009_trekking_estado_trekking_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekking',
            name='dificultad',
        ),
    ]
