# Generated by Django 5.0 on 2023-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0010_remove_trekking_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AddField(
            model_name='trekking',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trekking_imagenes/'),
        ),
    ]
