# Generated by Django 5.0 on 2023-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0011_comments_imagen_trekking_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekking',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='trekking',
            name='puntos_interes',
        ),
        migrations.AddField(
            model_name='trekking',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='facil', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios/'),
        ),
    ]
