# Generated by Django 5.0 on 2023-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0012_remove_trekking_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekking',
            name='dificultad',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], default='Fácil', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('En Curso', 'En Curso'), ('Cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
    ]
