# Generated by Django 5.0 on 2023-12-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0013_alter_trekking_dificultad_alter_trekking_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='estado',
            field=models.CharField(default='Abierto', max_length=50),
        ),
        migrations.AlterField(
            model_name='comments',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
