# Generated by Django 5.0 on 2023-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0014_comments_estado_alter_comments_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('En Curso', 'En Curso')], default='Abierto', max_length=50),
        ),
    ]
