# Generated by Django 5.0 on 2023-12-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0015_alter_comments_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trekking',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
