# Generated by Django 5.0 on 2023-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0016_comments_last_updated_trekking_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
