# Generated by Django 5.0 on 2023-12-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0017_alter_comments_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekking',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='trekking',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentario_imagenes/'),
        ),
    ]
