# Generated by Django 5.0 on 2023-12-14 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0018_remove_trekking_dificultad_remove_trekking_ubicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trekking',
            name='dificultad',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], default='Fácil', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='duracion_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
