# Generated by Django 5.0 on 2023-12-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInfinity', '0020_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
    ]
